/*
* Name          : Shift_OppLineHandler
* Author        : Shift CRM
* Description   : Trigger handler for opportunity products. Extends Shift_TriggerHandler framework for functionality
*
* Maintenance History:
* Date ------------ Name  ----  Version --- Remarks
* 08/26/2016     Bryce Batson     0.1       Initial
*/
public class Shift_OppLineHandler extends Shift_TriggerHandler{

	public override void beforeInsert() {
	}

	public override void beforeUpdate() {
	}
}